<!-- Footer -->
<div class="navbar fixed-bottom navbar-light bg-light">
    <div class="container">
      <p class="navbar-text pull-left">&copy <?php echo date('Y');?> - Duvan Rodriguez.
           <a href="#" target="_blank" style="color: #ecf0f1">Sitios Web y Sistemas</a>
      </p>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#" target='_blank'><i class="bi bi-envelope"></i> Soporte</a></li>
    </ul>

   </div>
</div>


<!--CDN JQUERY-->
<script
  src="https://code.jquery.com/jquery-3.6.0.slim.min.js"
  integrity="sha256-u7e5khyithlIdTpu22PHhENmPcRdFiHRjhAuHcs05RI="
  crossorigin="anonymous"></script>


    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <!-- Latest compiled and minified JavaScript -->

<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>

